name: ldm2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy
  - memory_profiler=0.61.0
  - tabulate=0.9.0
  - deepdish=0.3.7
  - hickle=3.4.5
  - prettyprinter=0.18.0
  - mahotas=1.4.13
  - microfilm=0.2.1
  - umap-learn=0.5.3
  - python_abi=3.8
  - datashader=0.15.1
  - holoviews=1.16.2
  - slack-sdk=3.19.5
  - albumentations=0.4.3
  - diffusers=0.11.0
  - pudb=2019.2
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.2
  - pytorch-lightning=1.4.2
  - omegaconf=2.1.1
  - streamlit>=0.73.1
  - einops=0.3.0
  - torch-fidelity=0.3.0
  - transformers=4.19.2
  - torchmetrics=0.6.0
  - kornia=0.6.9
  - tape_proteins=0.5
  - webdataset=0.2.26
  - ffmpeg
  - lzo=2.10
  - pip:
    - invisible-watermark==0.1.5
    - test-tube>=0.7.5
    - opencv-python-headless
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/haoxusci/pytorch_zoo@master#egg=pytorch_zoo
    - -e git+https://github.com/CellProfiling/HPA-Cell-Segmentation.git#egg=hpacellseg
    - -e .
