name: eval
channels:
  - pytorch
  - nvidia
  - conda-forge  
dependencies:
  - python=3.8
  - umap-learn
  - pip
  - pip:
    - setuptools==69.5.1
    - packaging
    - -e git+https://github.com/marcojira/fld.git@main#egg=fld