model:
  base_learning_rate: 1.15e-8 #4.6e-8 #1.15e-8 # learning rate with lr_scheduler #5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    #ckpt_path: /proj/aicell/data/stable-diffusion/mca/checkpoints/weights_ldm.ckpt
    ckpt_path: path/to/mca_ldm.ckpt
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "labels" # the key in the dataset for feeding into the condition model
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    #cond_stage_forward: true
    concat_mode: false # this will set conditioning_key to "crossattn" if not exists
    conditioning_key: crossattn # change to add the labels for mca
    scale_by_std: true
    monitor: 'val/loss_simple_ema'
    cond_dropout: 0.1

    #scheduler_config: 
    #   target: ldm.lr_scheduler.LambdaLinearScheduler
    #   params:
    #     warm_up_steps: [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1]
    #     cycle_lengths: [9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 1000000000000]
    #     f_start: [5.e-6, 5.e-6, 5.e-6, 5.e-6, 5.e-6, 5.e-6, 5.e-6, 5.e-6, 5.e-6, 5.e-6, 1.e-6]
    #     f_max: [ 5.e-5, 5.e-5, 5.e-5, 5.e-5, 5.e-5, 5.e-5, 5.e-5, 5.e-5, 5.e-5, 5.e-5, 1.e-6]
    #     f_min: [ 1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-6, 1.e-6]
         #verbosity_interval: 10000

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64 # 256/4
        in_channels: 3 
        out_channels: 3
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1, 2, 2, 4, 4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: True
        context_dim: 128 # must match the output of MCALabelEmbedder

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        #ckpt_path: /proj/aicell/data/stable-diffusion/mca/checkpoints/weights_autoencoder.ckpt
        ckpt_path: path/to/autoencoder.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.data.mca.MCAConditionEmbedder
      params:
        hidden_layers: [128]
        output_size_context_dim: 128
        


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8 # disable multiprocessing
    wrap: True # used to be True
    train:
      target: ldm.data.mca.MCACombineDataset
      params:
        directories: "/proj/aicell/data/stable-diffusion/mca/data/mitotic_cell_atlas_v1.0.1_fulldata/Data_tifs /proj/aicell/data/stable-diffusion/mca/data/ftp.ebi.ac.uk/pub/databases/IDR/idr0052-walther-condensinmap/20181113-ftp/MitoSys"
        cell_features: /proj/aicell/data/stable-diffusion/mca/labels/cell_features_necessary_columns.txt
        group: 'train' 
        use_cached_paths: True 
        cached_paths: /proj/aicell/data/stable-diffusion/mca/cache_paths/all-data-mca.json   
        normalization: True
        random_angle: True
    validation:
      target: ldm.data.mca.MCACombineDataset
      params:
        directories: "/proj/aicell/data/stable-diffusion/mca/data/mitotic_cell_atlas_v1.0.1_fulldata/Data_tifs /proj/aicell/data/stable-diffusion/mca/data/ftp.ebi.ac.uk/pub/databases/IDR/idr0052-walther-condensinmap/20181113-ftp/MitoSys"
        cell_features: /proj/aicell/data/stable-diffusion/mca/labels/cell_features_necessary_columns.txt
        group: 'validation'
        use_cached_paths: True
        cached_paths: /proj/aicell/data/stable-diffusion/mca/cache_paths/all-data-mca.json
        normalization: True
        random_angle: True

lightning:
  callbacks:
    image_logger:
      target: ldm.callbacks.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 3
        increase_log_steps: false
        log_images_kwargs:
          ddim_steps: 100
          quantize_denoised: true
          inpaint: false
          plot_denoise_rows: true
          plot_progressive_rows: true
          plot_diffusion_rows: true
          plot_inputs: true
          plot_reconstructions: true
          mix_sample: false
          n_row: 4

  trainer:
    benchmark: True
    accelerator: dp # need to change to dp because the default ddp will free the training
    #max_epochs: 3 # 1000 is default value for pl trainer
    val_check_interval: 0.1
    #fast_dev_run: True 
    #profiler: pytorch
    #limit_train_batches: 100
    #limit_val_batches: 1
    #resume_from_checkpoint: /proj/aicell/data/stable-diffusion/mca/checkpoints/weights_ldm.ckpt
    
