model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss
    #ckpt_path: models/first_stage_models/vq-f4/model.ckpt  # no ckpt available in repo

    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0
        n_classes: 8192

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    # num_workers: 0 # disable multiprocessing
    wrap: True
    train:
      target: ldm.data.mca.MCACombineDataset
      params:
        directories: '/proj/aicell/data/stable-diffusion/mca/mitotic_cell_atlas_v1.0.1_fulldata/Data_tifs /proj/aicell/data/stable-diffusion/mca/ftp.ebi.ac.uk/pub/databases/IDR/idr0052-walther-condensinmap/20181113-ftp/MitoSys'
        cell_features: '/data/ethyni/mca/cell_features_necessary_columns.txt'
        group: 'train'
        
    validation:
      target: ldm.data.mca.MCACombineDataset
      params:
        directories: '/proj/aicell/data/stable-diffusion/mca/mitotic_cell_atlas_v1.0.1_fulldata/Data_tifs /proj/aicell/data/stable-diffusion/mca/ftp.ebi.ac.uk/pub/databases/IDR/idr0052-walther-condensinmap/20181113-ftp/MitoSys'
        cell_features: '/data/ethyni/mca/cell_features_necessary_columns.txt'
        group: 'validation'

lightning:
  callbacks:
    image_logger:
      target: ldm.callbacks.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True
        log_first_step: False

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
    #profiler: simple
