model:
  base_learning_rate: 1 #5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: /proj/aicell/data/stable-diffusion/mca/logs/ldm-v1-round3-2024-04-15T13-03-57_mca_debug/checkpoints/epoch=000002.ckpt
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "labels" # the key in the dataset for feeding into the condition model
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    #cond_stage_forward: true
    concat_mode: false # this will set conditioning_key to "crossattn" if not exists
    conditioning_key: crossattn # change to add the labels for mca
    scale_by_std: true
    monitor: 'val/loss_simple_ema'

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64 # 256/4
        in_channels: 3 
        out_channels: 3
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1, 2, 2, 4, 4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: True
        context_dim: 128 # must match the output of MCALabelEmbedder

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        # pretrained autoencoder
        ckpt_path: /proj/aicell/data/stable-diffusion/mca/logs/ae-keep-2024-03-11T16-16-14_autoencoder_vq_f4_mca_data/checkpoints/epoch=000001-v1.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.data.mca.MCAConditionEmbedder
      params:
        hidden_layers: [128]
        output_size_context_dim: 128
        


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    #num_workers: 16 # disable multiprocessing
    wrap: True # used to be True
    test:
      target: ldm.data.mca.MCACombineDataset
      params:
        directories: "/proj/aicell/data/stable-diffusion/mca/mitotic_cell_atlas_v1.0.1_fulldata/Data_tifs /proj/aicell/data/stable-diffusion/mca/ftp.ebi.ac.uk/pub/databases/IDR/idr0052-walther-condensinmap/20181113-ftp/MitoSys"
        cell_features: /proj/aicell/data/stable-diffusion/mca/cell_features_necessary_columns.txt
        group: 'train' 
        use_cached_paths: True 
        cached_paths: /proj/aicell/data/stable-diffusion/mca/all-data-mca.json
        normalization: True
        random_angle: False
        train_val_split: 0.05
    
