model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    # ckpt_path: /data/wei/stable-diffusion/logs/2022-11-06T02-58-38_hpa-ldm-vq-4-hybrid-debug/checkpoints/last.ckpt
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "labels" # the key in the dataset for feeding into the condition model
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    #cond_stage_forward: true
    concat_mode: false # this will set conditioning_key to "crossattn" if not exists
    conditioning_key: crossattn # change to add the labels for mca
    scale_by_std: true
    monitor: 'val/loss_simple_ema'

    # scheduler_config: # 10000 warmup steps
    #   target: ldm.lr_scheduler.LambdaLinearScheduler
    #   params:
    #     warm_up_steps: [10000]
    #     cycle_lengths: [10000000000000]
    #     f_start: [1.e-6]
    #     f_max: [ 1.e-6 ]
    #     f_min: [ 1.e-6 ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64 # 256/4
        in_channels: 3 # why in_channels 6? should be 3 for me
        out_channels: 3
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1, 2, 2, 4, 4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: True
        context_dim: 128

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        # autoencoder for the reference + protein channel
        ckpt_path: /data/ethyni/stable-diffusion/logs/2024-03-01T15-36-00_autoencoder_vq_f4_mca/checkpoints/last.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.data.mca.MCALabelEmbedder
      params:
        place_holder_arg: True
        


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    # num_workers: 0 # disable multiprocessing
    wrap: True # used to be True
    train:
      target: ldm.data.mca.MCACombineDataset
      params:
        directories: "/data/ethyni/mca/mitotic_cell_atlas_v1.0.1_exampledata/Data_tifs"
        cell_features: "/data/ethyni/mca/mitotic_cell_atlas_v1.0.1_exampledata/Data_tifs/new_cell_features.txt"
        group: 'train' 
        use_cached_paths: False    
    validation:
      target: ldm.data.mca.MCACombineDataset
      params:
        directories: "/data/ethyni/mca/mitotic_cell_atlas_v1.0.1_exampledata/Data_tifs"
        cell_features: "/data/ethyni/mca/mitotic_cell_atlas_v1.0.1_exampledata/Data_tifs/new_cell_features.txt"
        group: 'validation'
        use_cached_paths: False

lightning:
  callbacks:
    image_logger:
      target: ldm.callbacks.ImageLogger
      params:
        batch_frequency: 10
        max_images: 4
        increase_log_steps: false
        log_images_kwargs:
          ddim_steps: 100
          quantize_denoised: true
          inpaint: false
          plot_denoise_rows: true
          plot_progressive_rows: false
          plot_diffusion_rows: true
          plot_inputs: false
          plot_reconstructions: false
          mix_sample: false
          n_row: 4

  trainer:
    benchmark: True
    accelerator: dp # need to change to dp because the default ddp will free the training
    # limit_val_batches: 100
    #fast_dev_run: 5
    #profiler: pytorch
    limit_train_batches: 100
    limit_val_batches: 10